//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string login { get; set; }
        public string password { get; set; }
        public int id_position { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string image { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
